language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

jobs:
  include:
    #    - stage: test
    #      install:
    #        - npm install
    #      script:
    #        - npm run build
    - stage: deploy
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install:
        - npm install
      script:
        - npm run build
      after_script:
        - npm publish
